# These are supported funding model platforms

github: [HemendraJawariya]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: HemendraJawariya
custom: https://buymeacoffee.com/hemendrajawariya